# Generated by Django 4.1 on 2022-08-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamCheckerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='username1', max_length=30),
            preserve_default=False,
        ),
    ]
