# Generated by Django 4.1 on 2022-08-10 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spamCheckerApp', '0003_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaldb',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spamCheckerApp.profile'),
        ),
    ]
