# Generated by Django 4.1 on 2022-08-10 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spamCheckerApp', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globaldb',
            name='parent',
        ),
    ]
