# Generated by Django 4.1 on 2022-08-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamCheckerApp', '0008_remove_globaldb_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaldb',
            name='spam_likelyhood',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
